version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    deploy: 
      resources:
        limits:
          cpus: "1"
          memory: "512MB"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: proxymitydb
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    deploy: 
      resources:
        limits:
          cpus: "1"
          memory: "512MB"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false