version: "3.4"

services:
  proxymity.server:
    container_name: "ProxyMity.Chat"
    image: ${DOCKER_REGISTRY-}proxymity-chat
    restart: always
    build:
      context: ../src
      dockerfile: ../src/ProxyMity.Chat/Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://+:5000"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1.5GB"
    depends_on:
      - postgres
    networks:
      - proxymity-chat-network

  postgres:
    container_name: "ProxyMity.Chat.Database"
    command: postgres -c 'max_connections=10'
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=proxymity_root
      - POSTGRES_PASSWORD=proxymity123
      - POSTGRES_DB=proxymitydb
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1.5GB"
    volumes:
      - ../volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - proxymity-chat-network

networks:
  proxymity-chat-network:
    driver: bridge
