import { Chat } from '@/@modules/chat/components/Chat';
import { ContactSidebar } from '@/@modules/chat/components/ContactSidebar';
import { ChatProvider } from '@/@modules/chat/contexts/chat-context/context';
import { ConversationDetail } from '@/@modules/chat/components/ConversationDetail';
import { EncryptionProvider } from '@/@modules/chat/contexts/encryption-context/context';

export const metadata = {
	title: 'ProxyMity - Chats',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.svg',
	},
};

export default function ChatPage() {
	return (
		<EncryptionProvider>
			<ChatProvider>
				<main className="flex flex-1 p-4 h-full gap-4 overflow-hidden m-auto max-w-[1980px] w-full">
					<ContactSidebar />
					<Chat />
					<ConversationDetail />
				</main>
			</ChatProvider>
		</EncryptionProvider>
	);
}
