version: '3.4'

services:
  proxymity.auth:
    container_name: "ProxyMity.Auth"
    image: ${DOCKER_REGISTRY-}proxymity-auth
    restart: always
    build:
      context: ../src
      dockerfile: ../src/ProxyMity.Auth/Dockerfile
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: "http://+:5001"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1.5GB"
    depends_on:
      - postgres
    networks:
      - proxymity-auth-network

  postgres:
    container_name: "ProxyMity.Auth.Database"
    command: postgres -c 'max_connections=10'
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=proxymity_root
      - POSTGRES_PASSWORD=proxymity123
      - POSTGRES_DB=proxymitydb
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1.5GB"
    volumes:
      - ../volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - proxymity-auth-network

networks:
  proxymity-auth-network:
    driver: bridge
