name: proxymity-deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    env:
      SSH_PRIVATE_KEY: ${{ vars.SERVER_SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
    environment:
      name: development
    steps:
      - name: Give VPS Access
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

      # - name: Enter on VPS
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ARGS: "-rlgoDzvc"
      #     REMOTE_HOST: ${{ secrets.SSH_HOST }}
      #     REMOTE_USER: ${{ secrets.SSH_USER }}
      #     SOURCE: "."
      #     TARGET: "/home/ubuntu/ProxyMity"

      - name: Copy Files to VPS
        run: |
          cat private_key
          scp -o StrictHostKeyChecking=no -i private_key -r * $SSH_USER@$SSH_HOST:/home/ubuntu/ProxyMity

      - name: Build Docker Compose on VPS
        run: ssh -i private_key $SSH_USER@$SSH_HOST "cd /home/ubuntu/ProxyMity && docker-compose up --build -d"

      - name: Copy Nginx Configuration on VPS
        run: scp -o StrictHostKeyChecking=no -i private_key nginx/proxy.conf $SSH_USER@$SSH_HOST:/etc/nginx/conf.d/proxy.conf

      - name: Restart Nginx on VPS
        run: ssh -i private_key $SSH_USER@$SSH_HOST "sudo systemctl restart nginx"
