name: proxymity-deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -r * $SSH_USER@$SSH_HOST:/ProxyMity
          ssh -i private_key $SSH_USER@$SSH_HOST "cd /ProxyMity && docker-compose up --build -d"
          scp -i private_key nginx/proxy.conf $SSH_USER@$SSH_HOST:/etc/nginx/conf.d/proxy.conf
          ssh -i private_key $SSH_USER@$SSH_HOST "sudo systemctl restart nginx"
